Config = {}
Config.Locale = GetConvar("esx:locale", "fr")

Config.CanDelete = true

if IsDuplicityVersion() then
    Config.Slots = 3

    Config.Prefix = "char"
else
    -- Positions des personnages (x, y, z, w = heading/orientation)
    -- Le slot 1 utilise la position 1, le slot 2 la position 2, etc.
    -- Si plus de slots que de positions, les positions tournent en boucle
    -- La caméra se place toujours automatiquement devant le personnage
    Config.CharacterPositions = {
        { x = -786.47, y = 331.39, z = 217.04, w = 174.91 },
        { x = -773.56, y = 325.95, z = 196.09, w = 349.21 },
        { x = -789.05, y = 333.22, z = 187.31, w = 166.58 },
        { x = -64.71, y = -807.89, z = 243.39, w = 251.30 },
    }

    -- Emotes aléatoires jouées lors de la sélection de personnage
    -- gender : "all" = homme + femme + peds custom, "m" = homme seulement, "f" = femme seulement
    Config.SelectionEmotes = {
        { name = "idle",      gender = "all" },
        { name = "idle3",  gender = "all" },
        { name = "idle11",  gender = "m" },
        { name = "idle12",     gender = "f" },
        { name = "idle13",   gender = "f" },
        { name = "idle14",      gender = "m" },
        { name = "idle15",  gender = "f" },
        { name = "idle16",  gender = "f" },
        { name = "idle17",  gender = "f" },
        { name = "idle18",  gender = "f" },
        { name = "idle9",  gender = "f" },
        { name = "idle7",  gender = "m" },
        { name = "idle6",  gender = "m" },
    }

    -- Durée du fondu lors du changement de position (ms)
    Config.TransitionDuration = 400

    Config.Relog = true

    Config.Default = {
        ["m"] = {
            mom = 43,
            dad = 29,
            grandparents = 0,
            face_md_weight = 61,
            skin_md_weight = 27,
            face_g_weight = 0,
            nose_1 = -5,
            nose_2 = 6,
            nose_3 = 5,
            nose_4 = 8,
            nose_5 = 10,
            nose_6 = 0,
            cheeks_1 = 2,
            cheeks_2 = -10,
            cheeks_3 = 6,
            lip_thickness = -2,
            jaw_1 = 0,
            jaw_2 = 0,
            chin_1 = 0,
            chin_2 = 0,
            chin_13 = 0,
            chin_4 = 0,
            neck_thickness = 0,
            hair_1 = 76,
            hair_2 = 0,
            hair_color_1 = 61,
            hair_color_2 = 29,
            tshirt_1 = 4,
            tshirt_2 = 2,
            torso_1 = 23,
            torso_2 = 2,
            decals_1 = 0,
            decals_2 = 0,
            arms = 1,
            arms_2 = 0,
            pants_1 = 28,
            pants_2 = 3,
            shoes_1 = 70,
            shoes_2 = 2,
            mask_1 = 0,
            mask_2 = 0,
            bproof_1 = 0,
            bproof_2 = 0,
            chain_1 = 22,
            chain_2 = 2,
            helmet_1 = -1,
            helmet_2 = 0,
            glasses_1 = 0,
            glasses_2 = 0,
            watches_1 = -1,
            watches_2 = 0,
            bracelets_1 = -1,
            bracelets_2 = 0,
            bags_1 = 0,
            bags_2 = 0,
            eye_color = 0,
            eye_squint = 0,
            eyebrows_2 = 0,
            eyebrows_1 = 0,
            eyebrows_3 = 0,
            eyebrows_4 = 0,
            eyebrows_5 = 0,
            eyebrows_6 = 0,
            makeup_1 = 0,
            makeup_2 = 0,
            makeup_3 = 0,
            makeup_4 = 0,
            lipstick_1 = 0,
            lipstick_2 = 0,
            lipstick_3 = 0,
            lipstick_4 = 0,
            ears_1 = -1,
            ears_2 = 0,
            chest_1 = 0,
            chest_2 = 0,
            chest_3 = 0,
            bodyb_1 = -1,
            bodyb_2 = 0,
            bodyb_3 = -1,
            bodyb_4 = 0,
            age_1 = 0,
            age_2 = 0,
            blemishes_1 = 0,
            blemishes_2 = 0,
            blush_1 = 0,
            blush_2 = 0,
            blush_3 = 0,
            complexion_1 = 0,
            complexion_2 = 0,
            sun_1 = 0,
            sun_2 = 0,
            moles_1 = 0,
            moles_2 = 0,
            beard_1 = 11,
            beard_2 = 10,
            beard_3 = 0,
            beard_4 = 0,
        },
        ["f"] = {
            mom = 28,
            dad = 6,
            grandparents = 0,
            face_md_weight = 63,
            skin_md_weight = 60,
            face_g_weight = 0,
            nose_1 = -10,
            nose_2 = 4,
            nose_3 = 5,
            nose_4 = 0,
            nose_5 = 0,
            nose_6 = 0,
            cheeks_1 = 0,
            cheeks_2 = 0,
            cheeks_3 = 0,
            lip_thickness = 0,
            jaw_1 = 0,
            jaw_2 = 0,
            chin_1 = -10,
            chin_2 = 10,
            chin_13 = -10,
            chin_4 = 0,
            neck_thickness = -5,
            hair_1 = 43,
            hair_2 = 0,
            hair_color_1 = 29,
            hair_color_2 = 35,
            tshirt_1 = 111,
            tshirt_2 = 5,
            torso_1 = 25,
            torso_2 = 2,
            decals_1 = 0,
            decals_2 = 0,
            arms = 3,
            arms_2 = 0,
            pants_1 = 12,
            pants_2 = 2,
            shoes_1 = 20,
            shoes_2 = 10,
            mask_1 = 0,
            mask_2 = 0,
            bproof_1 = 0,
            bproof_2 = 0,
            chain_1 = 85,
            chain_2 = 0,
            helmet_1 = -1,
            helmet_2 = 0,
            glasses_1 = 33,
            glasses_2 = 12,
            watches_1 = -1,
            watches_2 = 0,
            bracelets_1 = -1,
            bracelets_2 = 0,
            bags_1 = 0,
            bags_2 = 0,
            eye_color = 8,
            eye_squint = -6,
            eyebrows_2 = 7,
            eyebrows_1 = 32,
            eyebrows_3 = 52,
            eyebrows_4 = 9,
            eyebrows_5 = -5,
            eyebrows_6 = -8,
            makeup_1 = 0,
            makeup_2 = 0,
            makeup_3 = 0,
            makeup_4 = 0,
            lipstick_1 = 0,
            lipstick_2 = 0,
            lipstick_3 = 0,
            lipstick_4 = 0,
            ears_1 = -1,
            ears_2 = 0,
            chest_1 = 0,
            chest_2 = 0,
            chest_3 = 0,
            bodyb_1 = -1,
            bodyb_2 = 0,
            bodyb_3 = -1,
            bodyb_4 = 0,
            age_1 = 0,
            age_2 = 0,
            blemishes_1 = 0,
            blemishes_2 = 0,
            blush_1 = 0,
            blush_2 = 0,
            blush_3 = 0,
            complexion_1 = 0,
            complexion_2 = 0,
            sun_1 = 0,
            sun_2 = 0,
            moles_1 = 12,
            moles_2 = 8,
            beard_1 = 0,
            beard_2 = 0,
            beard_3 = 0,
            beard_4 = 0,
        },
    }
end
